[package]
name = "nyquest-backend-curl"
description = "libcurl backend for nyquest"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["ssl"]
async = ["nyquest/async"]
blocking = ["nyquest/blocking"]
ssl = ["curl/ssl"]

[dependencies]
nyquest = { path = "../..", default-features = false }
curl = { version = "0.4", default-features = false }
curl-sys = { version = "0.4", default-features = false }
