name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
    - name: Run clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
    - name: Run rustfmt
      run: cargo fmt --all --check

  test-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - name: Run tests
        run: wasm-pack test --node backends/reqwest --features async
